function getSettingDefault(cameraurl, email, deviceID, cameraname) {
  var appSettings = {
    uuid: deviceID,
    grUuid: email,
    streamCfg: {
      enableAudio: 1,
      enabled: 1,
      enableTelnet: 0,
      isHd: 0,
      mqttUrl: "tcp://pro.ambicam.com:1883", // Or use ConfigurationManager.AppSettings["mqttserver"] to get the value.
      publishUrl: cameraurl,
      telnetUrl: "telnet.ambicam.com:8888",
      fwUpdtTo: "a0",
    },
    timeCfg: {
      time: "00000000",
      tz: "STD:+5:30",
      timeZone: "Asia/Calcutta",
      dstmode: 0,
      autoupdate: 1,
      autoupdatetzonvif: 0,
      ntpserver: "time.ambicam.com",
      ntpinterval: 1,
      ntpenable: 1,
    },
    videoCh011: {
      bps: 512,
      fps: 20,
      gop: 60,
      brmode: 2,
      piclevel: 1,
      fixqplevel: 1,
      width: 1280,
      height: 720,
      bmainstream: 1,
      bfield: 0,
    },
    videoCh012: {
      bps: 256,
      fps: 15,
      gop: 60,
      brmode: 2,
      piclevel: 1,
      fixqplevel: 1,
      width: 640,
      height: 360,
      bmainstream: 1,
      bfield: 0,
    },
    videoCh013: {
      bps: 64,
      fps: 5,
      gop: 15,
      brmode: 2,
      piclevel: 4,
      fixqplevel: 4,
      width: 320,
      height: 180,
      bmainstream: 1,
      bfield: 0,
    },
    emailCfg: {
      emailserver: "smtp.gmail.com",
      emailport: 465,
      ssl: 1,
      logintype: 1,
      emailusername: "alerts@ambicam.com",
      emailpassword: "v|c{azo)>?6",
      from: "alerts@ambicam.com",
      to: email,
      subject: "Ambicam Motion Alert",
      text: "This is an ambicam email alert",
      attatchment: "",
    },
    displayCfg: {
      hue: 50,
      brightness: 50,
      saturation: 50,
      contrast: 50,
      ircutmode: 1,
    },
    osdCfg: {
      cont_0: "YYYY-MM-DD hh:mm:ss",
      cont_1: cameraname,
      fontsize: 1,
      h_0: 32,
      h_1: 32,
      rgncnt: 2,
      show_0: 1,
      show_1: 1,
      w_0: 304,
      w_1: 112,
      x_0: 928,
      x_1: 64,
      y_0: 32,
      y_1: 32,
    },
    imageCfg: {
      devno: 0,
      chn: 0,
      flip: 0,
      mirror: 0,
      wdr: 1,
    },
    recordCh011: {
      startTimerRec: 0,
      startManualRec: 1,
      singlefiletime: 300,
      enable: 0,
      filepath: "/bin/vs/sd/rec",
    },
    recordCh012: {
      startTimerRec: 0,
      startManualRec: 0,
      singlefiletime: 60,
      enable: 0,
      filepath: "/bin/vs/sd/rec",
    },
    recordSch: {
      workday: [0, -1, 0, -1, 0, -1],
      weekend: [0, -1, 0, -1, 0, -1],
      sun: [0, -1, 0, -1, 0, -1],
      mon: [0, -1, 0, -1, 0, -1],
      tue: [0, -1, 0, -1, 0, -1],
      wed: [0, -1, 0, -1, 0, -1],
      thu: [0, -1, 0, -1, 0, -1],
      fri: [0, -1, 0, -1, 0, -1],
      sat: [0, -1, 0, -1, 0, -1],
      rectime: 30,
      etm: 2,
    },
    mdCfg: {
      md_email_switch: 0,
      md_snap_switch: 1,
      md_emailsnap_switch: 0,
      md_ftpsnap_switch: 1,
      md_record_switch: 0,
      md_ftprec_switch: 0,
      md_ioalmdo_switch: 0,
      etm: 2,
      workday: 0,
      weekend: 0,
      md_interval: 30,
      MdbEnable: 0,
      MdSensitiValue: 1,
      MDThresholdValue: 10,
      MdInterval: 30,
      MdRegion: [
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        0, 0,
      ],
      md_alarm: 0,
      defend_alarm: 0,
      tc_alarm: 0,
    },
    devInfo: {
      hwVersion: 1,
      swVer: 1,
      provisioningVer: 1,
      publisherVer: 1,
      serialNo: "VVVIPC1504173580HSDS-j0TsuixTi4l"
    },
    nwInfo: {
      networktype: "NONE",
      macaddress: "00:00:00:00:00:00",
      ip: "0.0.0.0",
      netmask: "0.0.0.0",
      gateway: "0.0.0.0",
      sdnsip: "0.0.0.0",
      fdnsip: "0.0.0.0",
    },
    ptzinfo: {
      leftPos: 595,
      rightPos: 0,
      upPos: 0,
      downPos: 0,
      farPos: 0,
      nearPos: 0,
      currTiltPos: 0,
      currPanPos: 0,
      currZoomPos: 0,
    },
  };

  return appSettings;
}